In [2]:
import pandas as pd
ventas = pd.read_csv(
    "C:/Users/diego/Documents/primer_python/01-python-intro/data/ventas.csv" 
)

ventas.head()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [4]:
mascara = ventas["region"] == "Sur"
ventas_sur = ventas[mascara]
ventas_sur.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1156,2024-12-17,Sur,Luis Gomez,Teclado Mec,Accesorios,11,95,0.15
1163,2024-12-19,Sur,Luis Gomez,Silla Ergo,Mobiliario,2,280,0.00
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00
1191,2024-12-30,Sur,Luis Gomez,Silla Ergo,Mobiliario,3,280,0.00
1192,2024-12-30,Sur,Javier Sanz,Teclado Mec,Accesorios,8,95,0.10

In [7]:
ventas[ventas["region"] == "Sur"].head()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
14,2024-01-05,Sur,Pedro Diaz,Teclado Mec,Accesorios,12,95,0.05
21,2024-01-07,Sur,Marta Ruiz,Auriculares,Accesorios,4,130,0.10
22,2024-01-08,Sur,Elena Mora,Teclado Mec,Accesorios,3,95,0.00